### ISSUE TITLE
Fish issue

### ISSUE THREAD

**Issue by halfacookie** [corgidotcom/website#1]
### This is a request to put more fishes on the site please a lot of viewers like their fish and want to see it on the site (?)

**Comment by corgidotcom** [comment]
Welllll okay

**Comment by halfacookie** [comment]
> Welllll okay

Niice! nice dude! Yeah that's the kind uf support around here you don't see anymore like If I went to sony playstation's site and asked them if they could add more fish to the sight they would probably just not even respond but you are rocking on! Keep up the great work

**Comment by halfacookie** [comment]
SWEET AS A GREAT 11ab2db9c5520bb61e3e9d9ebf579db66052c64e closes this
