### ISSUE TITLE
New BLOMY WORLD!

### ISSUE THREAD

**Issue by halfacookie** [corgidotcom/website#4]
New BLUMEY world, coruy thung a ribung

**Comment by halfacookie** [comment]
Detes in the dete in the doovey

**Comment by corgidotcom** [comment]
Wow. I will incorporate this somehow. In the future

**Comment by corgidotcom** [comment]
blomy world can be achieved at the end of the fish storyline https://corgidot.com/blomyworld

**Comment by halfacookie** [comment]
**I'm happy**
