### ISSUE TITLE
Fish's pressure value can increase more than intended before button fades out

### ISSUE THREAD

**Issue by halfacookie** [corgidotcom/website#5]
When clicking "Where are you from?" more than once before the button fades out, the pressure value will continue to increase from these clicks, causing the fish to skip dialog. It is possible to skip the entire dialog this wayQò

**Comment by corgidotcom** [comment]
Thx I will fix that

**Comment by halfacookie** [comment]
You should not close an issue before a fix is appeared

**Comment by corgidotcom** [comment]
You know what, you're right. i don't know why I did that.

**Comment by corgidotcom** [comment]
Should be fix now okay [#87](https://github.com/corgidotcom/website/commit/6115e2cc38c9348b45a25fac78920aa5d2603171) fixes this
