### ISSUE TITLE
Fish's mushroom path is unachievable if you have a cool name

### ISSUE THREAD

**Issue by halfacookie** [corgidotcom/website#6]
**Idea** The fish tuns yellow if you done name is Pikachu(?) but you don't have to to it

**Comment by corgidotcom** [comment]
This is intentional

**Comment by halfacookie** [comment]
You closed it wrong because it's not completed it's won't fix

**Comment by corgidotcom** [comment]
Well actually, check it again

**Comment by halfacookie** [comment]
There's another way to close it and it's grey

**Comment by corgidotcom** [comment]
Okay

**Comment by halfacookie** [comment]
Yay
