### ISSUE TITLE
Fish's mushroom path is unachievable

### ISSUE THREAD

**Issue by halfacookie** [corgidotcom/website#7]
When generating the random value to determine if the user gets the mushroom path, the random value is not floored, making it a real number by default. This real number is then checked in a condition for if it is equal to or under 0, and since Math.random() does not generate negative numbers, it can not be under 0. Therefore, the only way for the condition to be true is for Math.random() * 100 to be exactly 0, which is practically impossible.

This can be fixed by either changing the condition to be equal to or under 1, or flooring the random value.

**Comment by halfacookie** [comment]
I made a floopy fisk

**Comment by halfacookie** [comment]
Aph

**Comment by corgidotcom** [comment]
This is because it's disabled Because its not FINISHED

**Comment by halfacookie** [comment]
(Now add the appropriate label and close the issue)

**Comment by corgidotcom** [comment]
I'm actualy okay this will stay unresolved

**Comment by halfacookie** [comment]
You never lern

**Comment by halfacookie** [comment]
You are a disgrace to the web site community

**Comment by halfacookie** [comment]
I'm sorry I didn't mean that we're just joking around

**Comment by corgidotcom** [comment]
Okay'thats good then

**Comment by halfacookie** [comment]
Yay let's be friends

**Comment by corgidotcom** [comment]
OKAY OKAY OKAY OKAY OKAY YAY

**Comment by corgidotcom** [comment]
implemented and working. mushroom path has a 10% chance on encounter. to be expanded upon in the future 😃
